name: Build

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - main # Trigger for pushes to main branch
    paths-ignore:
      - 'mkdocs.yml'
      - 'docs/**'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Lint app
        run: ./gradlew spotlessCheck --stacktrace

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Test app
        run: ./gradlew test --stacktrace

  api-check:
    name: 🕵️ API Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: API Check
        run: ./gradlew apiCheck --stacktrace

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build app
        run: ./gradlew :app:assemble --no-daemon --stacktrace
